Repository Kipper-Lang/Kipper, pull requests merged in 2022-10, with the labels that each got.

#321 Fixed Bug #319: Links open in new window
  tools/build/build-webpages.ts
Labels: fix, docs

#330 Variable type semantics bug in error recovery
  .eslintrc
  CHANGELOG.md
  README.md
  kipper/cli/README.md
  kipper/cli/src/errors.ts
  kipper/core/README.md
  kipper/core/src/antlr-error-listener.ts
  kipper/core/src/compiler/compiler.ts
  kipper/core/src/compiler/index.ts
  kipper/core/src/compiler/optimiser/optimiser.ts
  kipper/core/src/compiler/parser/compilable-ast-node.ts
  kipper/core/src/compiler/parser/root-ast-node.ts
  kipper/core/src/compiler/program-ctx.ts
  kipper/core/src/compiler/reference.ts
  kipper/core/src/compiler/runtime-built-ins.ts
  kipper/core/src/compiler/scope-declaration.ts
  kipper/core/src/compiler/semantics/const.ts
  kipper/core/src/compiler/semantics/language/definitions.ts
  kipper/core/src/compiler/semantics/language/expressions.ts
  kipper/core/src/compiler/semantics/language/statements.ts
  kipper/core/src/compiler/semantics/processor/semantic-checker.ts
  kipper/core/src/compiler/semantics/processor/type-checker.ts
  kipper/core/src/compiler/semantics/semantic-data/definitions.ts
  kipper/core/src/compiler/semantics/semantic-data/expressions.ts
  kipper/core/src/compiler/semantics/semantics-asserter.ts
  kipper/core/src/compiler/semantics/semantics-error-handler.ts
  kipper/core/src/compiler/semantics/type-data/definitions.ts
  kipper/core/src/compiler/semantics/type-data/expressions.ts
  kipper/core/src/compiler/semantics/type-data/statements.ts
  kipper/core/src/compiler/semantics/type.ts
  kipper/core/src/compiler/symbol-table/entry/index.ts
  kipper/core/src/compiler/symbol-table/entry/scope-declaration.ts
  kipper/core/src/compiler/symbol-table/entry/scope-function-declaration.ts
  kipper/core/src/compiler/symbol-table/entry/scope-parameter-declaration.ts
  kipper/core/src/compiler/symbol-table/entry/scope-variable-declaration.ts
  kipper/core/src/compiler/symbol-table/index.ts
  kipper/core/src/compiler/symbol-table/reference.ts
  kipper/core/src/compiler/symbol-table/scope/function-scope.ts
  kipper/core/src/compiler/symbol-table/scope/global-scope.ts
  kipper/core/src/compiler/symbol-table/scope/index.ts
  kipper/core/src/compiler/symbol-table/scope/local-scope.ts
  kipper/core/src/compiler/symbol-table/scope/scope.ts
  kipper/core/src/errors.ts
  kipper/core/src/index.ts
  kipper/core/src/utils.ts
  kipper/target-js/README.md
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/README.md
  kipper/target-ts/src/code-generator.ts
  kipper/target-ts/src/tools.ts
  kipper/web/README.md
  test/module/core/global-scope.test.ts
Labels: bug, fix, skip changelog, hacktoberfest, hacktoberfest-accepted

#333 Implemented unary and postfix operators `++` and `--`
  CHANGELOG.md
  README.md
  kipper/cli/README.md
  kipper/core/Kipper.g4
  kipper/core/README.md
  kipper/core/src/compiler/semantics/language/expressions.ts
  kipper/core/src/compiler/semantics/processor/type-checker.ts
  kipper/core/src/compiler/semantics/semantic-data/expressions.ts
  kipper/core/src/errors.ts
  kipper/target-js/README.md
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/README.md
  kipper/web/README.md
  test/module/core/core-functionality.test.ts
  test/module/core/errors.test.ts
Labels: feature, hacktoberfest, hacktoberfest-accepted
