Repository Kipper-Lang/Kipper, pull requests merged in 2023-07, with the labels that each got.

#484 Fixing invalid syntax in quickstart docs page
  src/docs/latest/quickstart.md
  src/docs/next/quickstart.md
Labels: skip changelog, docs

#483 Readme Style Update
  README.md
  kipper/cli/README.md
  kipper/core/README.md
  kipper/target-js/README.md
  kipper/target-ts/README.md
  kipper/web/README.md
  test/web-bundle-test.html
Labels: skip changelog, maintenance, docs

#487 Minor README.md content update
  README.md
  kipper/core/README.md
Labels: skip changelog, maintenance, docs

#488 Cleaned up `quickstart.md` in `latest` and `next`
  src/docs/latest/quickstart.md
  src/docs/next/quickstart.md
Labels: skip changelog, docs

#489 Standardised error output of the `@kipper/cli`
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  kipper/cli/src/commands/analyse.ts
  kipper/cli/src/commands/compile.ts
  kipper/cli/src/commands/help.ts
  kipper/cli/src/commands/run.ts
  kipper/cli/src/commands/version.ts
  kipper/cli/src/decorators.ts
  kipper/cli/src/errors.ts
  kipper/cli/src/index.ts
  kipper/cli/src/input/file-stream.ts
  kipper/cli/src/input/index.ts
  kipper/cli/src/input/target.ts
  kipper/cli/src/logger.ts
  kipper/cli/src/output/compile.ts
  kipper/cli/src/output/index.ts
  kipper/cli/tsconfig.json
  kipper/core/README.md
  kipper/core/src/errors.ts
  test/module/cli/analyse.test.ts
Labels: other

#486 v0.10.3
  CHANGELOG.md
  bump.sh
  kipper/cli/README.md
  kipper/cli/package.json
  kipper/cli/src/commands/analyse.ts
  kipper/cli/src/commands/compile.ts
  kipper/cli/src/commands/help.ts
  kipper/cli/src/commands/run.ts
  kipper/cli/src/commands/version.ts
  kipper/cli/src/decorators.ts
  kipper/cli/src/errors.ts
  kipper/cli/src/index.ts
  kipper/cli/src/input/file-stream.ts
  kipper/cli/src/input/index.ts
  kipper/cli/src/input/target.ts
  kipper/cli/src/logger.ts
  kipper/cli/src/output/compile.ts
  kipper/cli/src/output/index.ts
  kipper/cli/tsconfig.json
  kipper/core/package.json
  kipper/core/src/errors.ts
  kipper/core/src/index.ts
  kipper/index.ts
  kipper/target-js/package.json
  kipper/target-js/src/index.ts
  kipper/target-ts/package.json
  kipper/target-ts/src/index.ts
  kipper/web/package.json
  package.json
  test/module/cli/analyse.test.ts
Labels: bug, other, release, fix
