Repository Kipper-Lang/Kipper, pull requests merged in 2024-07, with the labels that each got.

#533 Implemented do-while loop statement
  CHANGELOG.md
  kipper/core/src/compiler/ast/nodes/statements/iteration-statement/do-while-loop-iteration-statement/do-while-loop-iteration-statement-semantics.ts
  kipper/core/src/compiler/ast/nodes/statements/iteration-statement/do-while-loop-iteration-statement/do-while-loop-iteration-statement.ts
  kipper/core/src/compiler/program-ctx.ts
  kipper/target-js/src/code-generator.ts
  test/kipper-files/do-while-loop.kip
  test/module/core/compiler.test.ts
  test/module/core/core-functionality.test.ts
Labels: feature

#535 Removed command `analyse` and replaced it with `compile` command `--dry-run` flag
  CHANGELOG.md
  kipper/cli/src/commands/analyse.ts
  kipper/cli/src/commands/compile.ts
  test/module/cli/analyse.test.ts
Labels: other

#565 Implemented ternary conditional expression
  .run/antlr4.run.xml
  CHANGELOG.md
  kipper/core/src/compiler/analysis/analyser/type-checker.ts
  kipper/core/src/compiler/ast/nodes/expressions/conditional-expression/conditional-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/conditional-expression/conditional-expression.ts
  kipper/target-js/src/code-generator.ts
  test/module/core/core-functionality.test.ts
  test/module/core/not-implemented.test.ts
Labels: feature

#649 v0.11.0-alpha.8
  kipper/cli/README.md
  kipper/cli/package.json
  kipper/cli/pnpm-lock.yaml
  kipper/cli/src/index.ts
  kipper/config/package.json
  kipper/config/src/index.ts
  kipper/core/package.json
  kipper/core/src/index.ts
  kipper/index.ts
  kipper/target-js/package.json
  kipper/target-js/src/index.ts
  kipper/target-ts/package.json
  kipper/target-ts/src/index.ts
  kipper/web/package.json
  package.json
Labels: release, skip changelog

#650 Implemented Lambda Expressions
  .run/kipper run.run.xml
  CHANGELOG.md
  kipper/cli/README.md
  kipper/cli/pnpm-lock.yaml
  kipper/core/KipperParser.g4
  kipper/core/package.json
  kipper/core/src/compiler/analysis/analyser/semantic-checker.ts
  kipper/core/src/compiler/analysis/analyser/type-checker.ts
  kipper/core/src/compiler/analysis/analyser/warning-issuer.ts
  kipper/core/src/compiler/analysis/symbol-table/entry/scope-parameter-declaration.ts
  kipper/core/src/compiler/analysis/symbol-table/function-scope.ts
  kipper/core/src/compiler/analysis/symbol-table/lambda-scope.ts
  kipper/core/src/compiler/ast/ast-generator.ts
  kipper/core/src/compiler/ast/common/ast-types.ts
  kipper/core/src/compiler/ast/compilable-ast-node.ts
  kipper/core/src/compiler/ast/mapping/ast-node-mapper.ts
  kipper/core/src/compiler/ast/nodes/declarations/function-declaration/function-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/parameter-declaration/parameter-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/parameter-declaration/parameter-declaration.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic/arithmetic-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/assignment-expression/assignment-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/bitwise-expression/bitwise-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/cast-or-convert-expression/cast-or-convert-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/comparative-expression/comparative-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/conditional-expression/conditional-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/function-call-expression/function-call-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/lambda-expression/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/lambda-expression/lambda-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/lambda-expression/lambda-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/lambda-expression/lambda-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/logical-expression/logical-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/member-access-expression/member-access-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/postfix-expression/postfix-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/fstring-primary-expression/fstring-primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/type-specifier-expression/type-specifier-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/unary-expression/unary-expression.ts
  kipper/core/src/compiler/ast/nodes/statements/return-statement/return-statement-semantics.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParser.interp
  kipper/core/src/compiler/lexer-parser/antlr/KipperParser.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParserListener.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParserVisitor.ts
  kipper/core/src/compiler/lexer-parser/parse-rule-kind-mapping.ts
  kipper/core/src/compiler/target-presets/semantic-analyser.ts
  kipper/core/src/compiler/target-presets/translation/code-generator.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-js/src/semantic-analyser.ts
  pnpm-lock.yaml
  test/kipper-files/lambda-expressions.kip
  test/module/core/errors/index.ts
  test/module/core/errors/type-errors/lambda-expression.ts
Labels: feature

#651 Removed deprecated flag `--abort-on-first-error`
  CHANGELOG.md
  kipper/cli/src/commands/compile.ts
  kipper/cli/src/commands/run.ts
  kipper/cli/src/decorators.ts
  kipper/cli/src/input/input-file.ts
  kipper/config/src/evaluated-kipper-config-file.ts
Labels: other

#653 v0.11.0-rc.0
  CITATION.cff
  kipper/cli/README.md
  kipper/cli/package.json
  kipper/cli/src/index.ts
  kipper/config/package.json
  kipper/config/src/index.ts
  kipper/core/package.json
  kipper/core/src/index.ts
  kipper/index.ts
  kipper/target-js/package.json
  kipper/target-js/src/index.ts
  kipper/target-ts/package.json
  kipper/target-ts/src/index.ts
  kipper/web/package.json
  package.json
Labels: release, skip changelog

#660 Added full object support and translation for JavaScript & TypeScript targets
  CHANGELOG.md
  kipper/core/src/compiler/ast/ast-generator.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-primary-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-property/object-property-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-property/object-property.ts
  kipper/core/src/compiler/semantics/types/custom-type.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/src/code-generator.ts
  test/module/core/core-functionality.test.ts
Labels: feature

#673 Implemented `Func<T..., R>` generic function type and auto-function type inference
  .nycrc.json
  CHANGELOG.md
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/lambda-primary-expression/lambda-primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/type-specifier-expression/generic-type-specifier-expression/generic-type-specifier-expression.ts
  kipper/core/src/compiler/semantics/analyser/type-checker.ts
  kipper/core/src/compiler/semantics/symbol-table/universum-scope.ts
  kipper/core/src/compiler/semantics/types/base/generic-built-in-type.ts
  kipper/core/src/compiler/semantics/types/base/generic-type.ts
  kipper/core/src/compiler/semantics/types/base/processed-type.ts
  kipper/core/src/compiler/semantics/types/built-in/array.ts
  kipper/core/src/compiler/semantics/types/built-in/func.ts
  kipper/core/src/errors.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/src/code-generator.ts
  kipper/target-ts/src/target.ts
  test/module/core/core-functionality.test.ts
  test/module/core/errors/type-errors/mismatching-arg-count-between-func-types.ts
Labels: feature, breaking change

#675 Added classes with class properties, class methods and constructors
  CHANGELOG.md
  kipper/cli/README.md
  kipper/core/KipperLexer.g4
  kipper/core/KipperLexer.tokens
  kipper/core/KipperParser.g4
  kipper/core/KipperParser.tokens
  kipper/core/src/compiler/ast/ast-generator.ts
  kipper/core/src/compiler/ast/common/ast-types.ts
  kipper/core/src/compiler/ast/mapping/ast-node-mapper.ts
  kipper/core/src/compiler/ast/nodes/declarations/parameter-declaration/parameter-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-constructor-declaration/class-constructor-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-constructor-declaration/class-constructor-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-constructor-declaration/class-constructor-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-constructor-declaration/index.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-member-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-member-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-member-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-method-declaration/class-method-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-method-declaration/class-method-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-method-declaration/class-method-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-method-declaration/index.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-property-declaration/class-property-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-property-declaration/class-property-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-property-declaration/class-property-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-property-declaration/index.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/index.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/index.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/interface-declaration/interface-member-declaration/interface-member-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/type-declaration.ts
  kipper/core/src/compiler/const.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperLexer.interp
  kipper/core/src/compiler/lexer-parser/antlr/KipperLexer.tokens
  kipper/core/src/compiler/lexer-parser/antlr/KipperLexer.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParser.interp
  kipper/core/src/compiler/lexer-parser/antlr/KipperParser.tokens
  kipper/core/src/compiler/lexer-parser/antlr/KipperParser.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParserListener.ts
  kipper/core/src/compiler/lexer-parser/antlr/KipperParserVisitor.ts
  kipper/core/src/compiler/lexer-parser/parse-rule-kind-mapping.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-parameter-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/function-scope.ts
  kipper/core/src/compiler/semantics/types/built-in/func.ts
  kipper/core/src/compiler/target-presets/semantic-analyser.ts
  kipper/core/src/compiler/target-presets/translation/code-generator.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-js/src/semantic-analyser.ts
  kipper/target-ts/src/code-generator.ts
  test/module/core/core-functionality.test.ts
Labels: feature

#676 Add support for built-in constant `NaN`
  CHANGELOG.md
  kipper/core/src/compiler/semantics/symbol-table/universum-scope.ts
  kipper/core/src/compiler/semantics/types/built-in/func.ts
  kipper/core/src/compiler/target-presets/translation/built-ins-generator.ts
  kipper/target-js/src/built-in-generator.ts
  kipper/target-ts/src/built-in-generator.ts
  test/module/core/built-ins.test.ts
Labels: feature

#677 Implemented index-based array assignments
  CHANGELOG.md
  kipper/core/src/compiler/ast/nodes/declarations/function-declaration/function-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/function-declaration/function-declaration.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/additive-expression/additive-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/additive-expression/additive-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/additive-expression/additive-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/additive-expression/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/arithmetic-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/arithmetic-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/arithmetic-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/multiplicative-expression/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/multiplicative-expression/multiplicative-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/multiplicative-expression/multiplicative-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/arithmetic-expression/multiplicative-expression/multiplicative-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/assignment-expression/assignment-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/assignment-expression/assignment-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/function-call-expression/function-call-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/function-call-expression/function-call-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/index.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/identifier-primary-expression/identifier-primary-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/identifier-primary-expression/identifier-primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/lambda-primary-expression/lambda-primary-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/lambda-primary-expression/lambda-primary-expression.ts
  kipper/core/src/compiler/optimiser/optimiser.ts
  kipper/core/src/compiler/program-ctx.ts
  kipper/core/src/compiler/semantics/analyser/semantic-checker.ts
  kipper/core/src/compiler/semantics/analyser/type-checker.ts
  kipper/core/src/compiler/semantics/reference.ts
  kipper/core/src/compiler/semantics/runtime-built-ins/built-in-function.ts
  kipper/core/src/compiler/semantics/runtime-internals/internal-function.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-function-declaration.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/src/code-generator.ts
  kipper/target-ts/src/tools.ts
  test/module/core/core-functionality.test.ts
  test/module/core/errors/semantic-errors/builtin-overwrite.ts
  test/module/core/errors/semantic-errors/invalid-global.ts
  test/module/core/program-ctx.test.ts
Labels: feature

#678 Added support for dot notation member access syntax (`parent.field`)
  CHANGELOG.md
  kipper/core/src/compiler/ast/ast-generator.ts
  kipper/core/src/compiler/ast/nodes/declarations/function-declaration/function-declaration-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-declaration-semantics.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-member-declaration/class-member-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/interface-declaration/interface-declaration.ts
  kipper/core/src/compiler/ast/nodes/expressions/assignment-expression/assignment-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/member-access-expression/member-access-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/lambda-primary-expression/lambda-primary-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-primary-expression-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-primary-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-property/object-property-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/object-primary-expression/object-property/object-property.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/string-primary-expression/string-primary-expression.ts
  kipper/core/src/compiler/ast/scope-node.ts
  kipper/core/src/compiler/const.ts
  kipper/core/src/compiler/semantics/analyser/type-checker.ts
  kipper/core/src/compiler/semantics/runtime-built-ins/built-in-function-argument.ts
  kipper/core/src/compiler/semantics/runtime-built-ins/built-in-variable.ts
  kipper/core/src/compiler/semantics/runtime-internals/internal-function-argument.ts
  kipper/core/src/compiler/semantics/runtime-internals/internal-function.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-function-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/global-scope.ts
  kipper/core/src/compiler/semantics/symbol-table/universum-scope.ts
  kipper/core/src/compiler/semantics/types/base/generic-built-in-type.ts
  kipper/core/src/compiler/semantics/types/base/processed-type.ts
  kipper/core/src/compiler/semantics/types/built-in/array.ts
  kipper/core/src/compiler/semantics/types/built-in/index.ts
  kipper/core/src/compiler/semantics/types/built-in/obj.ts
  kipper/core/src/compiler/semantics/types/custom-type.ts
  kipper/core/src/compiler/target-presets/translation/code-generator.ts
  kipper/core/src/errors.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-js/src/semantic-analyser.ts
  kipper/target-ts/src/target.ts
  test/module/core/core-functionality.test.ts
  test/module/core/errors/semantic-errors/invalid-global.ts
Labels: feature

#680 Implemented support for arrays in built-in function `len()`
  CHANGELOG.md
  kipper/core/src/compiler/ast/nodes/declarations/function-declaration/function-declaration.ts
  kipper/core/src/compiler/ast/nodes/declarations/type-declaration/class-declaration/class-declaration-semantics.ts
  kipper/core/src/compiler/program-ctx.ts
  kipper/core/src/compiler/semantics/runtime-internals/internal-function-argument.ts
  kipper/core/src/compiler/semantics/runtime-internals/internals.ts
  kipper/core/src/compiler/semantics/symbol-table/universum-scope.ts
  kipper/core/src/compiler/semantics/types/base/built-in-type.ts
  kipper/core/src/compiler/semantics/types/base/index.ts
  kipper/core/src/compiler/semantics/types/base/processed-type.ts
  kipper/core/src/compiler/semantics/types/base/union-type.ts
  kipper/core/src/compiler/semantics/types/built-in/any.ts
  kipper/core/src/compiler/semantics/types/built-in/array.ts
  kipper/core/src/compiler/semantics/types/built-in/func.ts
  kipper/core/src/compiler/semantics/types/built-in/index.ts
  kipper/core/src/compiler/target-presets/semantic-analyser.ts
  kipper/core/src/compiler/target-presets/translation/built-ins-generator.ts
  kipper/core/src/errors.ts
  kipper/target-ts/src/built-in-generator.ts
  kipper/target-ts/src/target.ts
  kipper/target-ts/src/tools.ts
  test/module/core/built-ins.test.ts
  test/module/core/core-functionality.test.ts
  test/module/core/errors/type-errors/argument-type.ts
Labels: feature

#681 Implemented function calls from lambdas, stored variables and expressions
  CHANGELOG.md
  kipper/cli/src/decorators.ts
  kipper/core/src/compiler/ast/nodes/expressions/function-call-expression/function-call-expression-type-semantics.ts
  kipper/core/src/compiler/ast/nodes/expressions/function-call-expression/function-call-expression.ts
  kipper/core/src/compiler/ast/nodes/expressions/primary-expression/lambda-primary-expression/lambda-primary-expression.ts
  kipper/core/src/compiler/semantics/analyser/type-checker.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-function-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-parameter-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-type-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/entry/scope-variable-declaration.ts
  kipper/core/src/compiler/semantics/symbol-table/global-scope.ts
  kipper/core/src/compiler/semantics/symbol-table/index.ts
  kipper/core/src/compiler/semantics/symbol-table/universe-scope.ts
  kipper/core/src/compiler/semantics/types/built-in/func.ts
  kipper/target-js/src/code-generator.ts
  kipper/target-ts/src/target.ts
  test/module/core/not-implemented.test.ts
Labels: feature
